version: '3.0'
services:
  postgresa:
    image: postgres:13
    container_name: 'postgresa-container'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgresusera
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=connectoradb
    volumes:
      - connector-dataa:/var/lib/postgresql/data
    networks:
      - local

  connector:
    image: ghcr.io/advanced-dataspaces-vtt/vtt-example-ids-connector/vtt-connector:simplified_compose
    container_name: vtt-connector
    ports:
      - 8081:8081
    environment:
      - CONFIGURATION_PATH=/config/config.json
      - SERVER_PORT=8081
      - DAPS_URL=https://daps.collab-cloud.eu/auth
      - DAPS_TOKEN_URL=https://daps.collab-cloud.eu/auth/token
      - DAPS_KEY_URL=https://daps.collab-cloud.eu/auth/jwks.json
      - DAPS_INCOMING_DAT_DEFAULT_WELLKNOWN=/jwks.json
      - SERVER_SSL_KEY-STORE=/config/collab-cloud.p12
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=password
      # Define the PostgreSQL setup
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresa:5432/connectoradb
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=postgresusera
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - local
    depends_on:
      - postgresa


  ui:
    image: ryankford/vtt-example-connector-ui:latest-amd64
    container_name: 'vtt-connector-ui'
    environment:
      - CONNECTOR_URL=https:130.188.160.22//:8081
      - CONNECTOR_USER=admin
      - CONNECTOR_PASSWORD=password
    ports:
      - 8080:8083
    networks:
      - local
    depends_on:
      - connector

volumes:
  connector-dataa: {}

networks:
  local:
    driver: bridge
